### ISSUE TITLE
lein plugin

### ISSUE THREAD

**Issue by belucid** [mynomoto/repetition-hunter#4]
Looks great!

Would love this to be a lein plugin though that ran from the commandline and automatically included all the namespaces from the project.

**Comment by nez** [comment]
Hey =) I managed to make a lein plugin that uses repetition-hunter.

It is in https://github.com/fractalLabs/lein-repetition-hunter 

I basically copied lein-kibit

**Comment by mynomoto** [comment]
This is cool, I just tried it! Thanks @nez ! I'm closing this and will add a link on the readme.
